# Generated by Django 6.1.2 on 2026-10-06 15:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perito',
            fields=[
                ('id_perito', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('especialidad', models.CharField(max_length=150)),
                ('zona', models.CharField(max_length=150)),
                ('carga_activa', models.PositiveIntegerField(default=0)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'perito',
                'indexes': [models.Index(fields=['zona', 'especialidad'], name='idx_perito_zona_especialidad')],
                'constraints': [models.CheckConstraint(condition=models.Q(('carga_activa__gte', 0)), name='chk_perito_carga_activa')],
            },
        ),
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id_inspeccion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_siniestro', models.UUIDField()),
                ('scheduled_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('report_url', models.TextField(blank=True, null=True)),
                ('findings', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('programada', 'Programada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='programada', max_length=20)),
                ('perito', models.ForeignKey(db_column='id_perito', on_delete=django.db.models.deletion.PROTECT, related_name='inspecciones', to='peritaje.perito')),
            ],
            options={
                'db_table': 'inspeccion',
                'indexes': [models.Index(fields=['perito'], name='idx_inspeccion_perito'), models.Index(fields=['id_siniestro'], name='idx_inspeccion_siniestro')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['programada', 'completada', 'cancelada'])), name='chk_inspeccion_status')],
            },
        ),
    ]
